name: Python Testing Pipeline 🧪

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=src --cov-report=term-missing --cov-report=xml

      - name: Upload coverage report summary
        run: |
          echo "### ✅ Test Results" >> $GITHUB_STEP_SUMMARY
          pytest --cov=src --cov-report=term >> $GITHUB_STEP_SUMMARY

      - name: Upload HTML coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
